config/routes.rb
Rails.application.routes.draw do
  get 'factures/index'

  get 'factures/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{:registrations=>'registrations',
             :confirmations=>'confirmations'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'pages#home'
  resources :users, only: [:show]
  resources :entreprises do
    resources :reservations, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end


  resources :subscribers
  resources :premiums
  resources :contacts, only: [:new, :create]

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  get 'vos_rendez_vous' => 'reservations#your_rdv'
  get 'vos_reservations' => 'reservations#your_reservations'

  get '/search' => 'pages#search'
  get '/faq' => 'pages#faq'
  get '/equipe' => 'pages#equipe'
  get '/services' => 'pages#services'
  get '/success' => 'pages#success'
  get '/abonnement' => 'pages#abonnement'
  get '/accueilsaas' => 'pages#homesaas'
  get '/politique-de-confidentialite' => "pages#politique"
  get '/mentions-legales' => "pages#mentions"
  get '/cgv' => "pages#cgv"

  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format" => "pages#robots"

  resources :factures, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,     :validate => true
  attribute :email,     :validate => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  attribute :sujet,     :validate => true
  attribute :message,     :validate => true

  def headers
    {
        :subject => "Formulaire de contact",
        :to => "edgar.bekier@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :sender, foreign_key: :sender_id, class_name:'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR
     (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/models/entreprise.rb
class Entreprise < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :delete_all
  has_many :reservations, dependent: :delete_all
  has_many :reviews, dependent: :delete_all

  validates :artisan_type, presence: true
  validates :company_name, presence: true
  validates :address, presence: true
  validates :legal_form, presence: true
  validates :siren, presence: true, length: {maximum: 9}
  validates :phone, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

end

app/models/facture.rb
class Facture < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :entreprise

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :entreprise
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :entreprise
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :fullname, presence:true, length: {maximum: 50}

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :entreprises, dependent: :delete_all
  has_many :reservations, dependent: :delete_all
  has_many :reviews, dependent: :delete_all
  has_many :factures, dependent: :delete_all
  has_many :messages, dependent: :delete_all
end

app/controllers/entreprises_controller.rb
class EntreprisesController < ApplicationController

  before_action :set_entreprise, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @entreprises = current_user.entreprises
  end

  def new
    @entreprise = current_user.entreprises.build
  end

  def create
    @entreprise = current_user.entreprises.build(entreprise_params)
    if @entreprise.save
      if params[:images]
        params[:images].each do |i|
          @entreprise.photos.create(image: i)
        end
      end
      @photos = @entreprise.photos
      redirect_to edit_entreprise_path(@entreprise), notice:"Votre entreprise a été ajouté avec succès"
    else
      render :new
    end
  end

  def show
    @photos = @entreprise.photos
    @reviews = @entreprise.reviews
    @booked = Reservation.where("entreprise_id = ? AND user_id = ?", @entreprise.id, current_user).present?
    if current_user
      @reviews = @entreprise.reviews
      @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
    end
  end

  def edit
    @photos = @entreprise.photos
  end

  def update
    if @entreprise.update(entreprise_params)
      if params[:images]
        params[:images].each do |i|
          @entreprise.photos.create(image: i)
        end
      end
      @photos = @entreprise.photos
      redirect_to edit_entreprise_path(@entreprise), notice:"Modifications enregistrée..."
    else
      render :edit
    end
  end

  def destroy
    @entreprise.destroy

    redirect_to entreprises_path
  end

  private
  def set_entreprise
    @entreprise = Entreprise.find(params[:id])
  end

  def entreprise_params
    params.require(:entreprise).permit(:artisan_type, :company_name, :code_naf, :siren, :siret, :address, :phone, :legal_form, :linkweb, :is_card, :is_cheque, :is_cash, :active, :summary)
  end

  def require_same_user
    if current_user.id != @entreprise.user_id
      flash[:danger] = "Vous n'avez pas le droit de modifier cette entreprise"
      redirect_to root_path
    end
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/entreprises_helper.rb
module EntreprisesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/premiums_helper.rb
module PremiumsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entreprises/_form.html.erb
<% unless current_page?(new_entreprise_path) %>
<!-- Hero Start -->
<section class="bg-half bg-light d-table w-100">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12 text-center">
        <div class="page-next-level">
          <h4 class="title"> Modifier votre entreprise</h4>
          <div class="page-next">
            <nav aria-label="breadcrumb" class="d-inline-block">
              <ul class="breadcrumb bg-white rounded shadow mb-0">
                <li class="breadcrumb-item"><%= link_to 'Accueil', root_path %></li>
                <!--<li class="breadcrumb-item"><a href="#">Page</a></li>-->
                <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Mes entreprises', entreprises_path, :class => "breadcrumb-item active" %></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>  <!--end col-->
    </div><!--end row-->
  </div> <!--end container-->
</section><!--end section-->
<!-- Hero End -->

<% else %>
  <!-- Hero Start -->
  <section class="bg-half bg-light d-table w-100">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12 text-center">
          <div class="page-next-level">
            <h4 class="title"> Ajouter votre entreprise sur Reparee </h4>
            <div class="page-next">
              <nav aria-label="breadcrumb" class="d-inline-block">
                <ul class="breadcrumb bg-white rounded shadow mb-0">
                  <li class="breadcrumb-item"><%= link_to 'Accueil', root_path %></li>
                  <!--<li class="breadcrumb-item"><a href="#">Page</a></li>-->
                  <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Ajout entreprise', new_entreprise_path, :class => "breadcrumb-item active" %></li>
                </ul>
              </nav>
            </div>
          </div>
        </div>  <!--end col-->
      </div><!--end row-->
    </div> <!--end container-->
  </section><!--end section-->
  <!-- Hero End -->
<% end %>

<!-- Page Content -->
<div class="content">
  <h1 class="titre-faq">Modifier votre entreprise</h1>
  <div class="container-fluid">
    <div class="row">
      <!-- Profile Sidebar -->
      <%= form_for @entreprise, html: {multipart: true} do |f| %>

      <div class="col-md-12 col-lg-12 col-xl-12">
        <div class="card">
          <div class="card-body">

            <!-- Profile Settings Form -->

              <form>
                <div class="row form-row">
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label>Nom de votre entreprise</label>
                      <%= f.text_field :company_name, placeholder:"Nom de la société", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label>Type d'entreprise</label>
                      <%= f.select :artisan_type, [["Plombier","Plombier"],["Serrurier","Serrurier"]], id: "artisan_type", prompt:"A sélectionner...", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label>Forme juridique</label>
                      <%= f.text_field :legal_form, placeholder:"Forme juridique", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label>Téléphone</label>
                      <%= f.text_field :phone, placeholder:"Téléphone", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <label>Adresse</label>
                      <%= f.text_field :address, placeholder:"Siège social de la société", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <span class="btn btn-default btn-file">
                        Téléchargez vos photos !
                      </span>
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </div>
                    <div id="photos"><%= render 'photos/list' %></div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label>SIREN</label>
                      <%= f.text_field :siren, placeholder:"SIREN", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label>SIRET</label>
                      <%= f.text_field :siret, placeholder:"SIRET", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label>Code NAF</label>
                      <%= f.text_field :code_naf, placeholder:"Code NAF", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div class="form-group">
                      <label>Lien site internet</label>
                      <%= f.text_field :linkweb, placeholder:"http://monsite.com", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <label>Description</label>
                      <%= f.text_field :summary, placeholder:"Description de votre entreprise", class:"form-control" %>
                    </div>
                  </div>
                  <div class="col-12 col-md-4">
                    <div class="form-group">
                      <%= f.check_box :is_card %>Carte bancaire
                    </div>
                  </div>
                  <div class="col-12 col-md-4">
                    <div class="form-group">
                      <%= f.check_box :is_cheque %>Chèque
                    </div>
                  </div>
                  <div class="col-12 col-md-4">
                    <div class="form-group">
                      <%= f.check_box :is_cash %>Espèce
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <%= f.check_box :active %>Entreprise active
                    </div>
                  </div>
                </div>
                <div class="submit-section">
                  <%= f.submit "Je valide mon entreprise", class:"btn btn-primary submit-btn" %>
                </div>
              </form>

      <% end %>
            <!-- /Profile Settings Form -->

          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<!-- /Page Content -->

app/views/entreprises/edit.html.erb
<%= render 'form' %>

app/views/entreprises/index.html.erb
<%= content_for :meta_title, "Liste de vos entreprises| #{DEFAULT_META["meta_title"]}" %>
<%= content_for :meta_description, "Liste de vos entreprises | #{DEFAULT_META["meta_description"]}" %>
<!-- Hero Start -->
<section class="bg-half bg-light d-table w-100">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12 text-center">
        <div class="page-next-level">
          <h4 class="title"> Mes entreprises </h4>
          <div class="page-next">
            <nav aria-label="breadcrumb" class="d-inline-block">
              <ul class="breadcrumb bg-white rounded shadow mb-0">
                <li class="breadcrumb-item"><%= link_to 'Accueil', root_path %></li>
                <!--<li class="breadcrumb-item"><a href="#">Page</a></li>-->
                <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Mes entreprises', entreprises_path, :class => "breadcrumb-item active" %></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>  <!--end col-->
    </div><!--end row-->
  </div> <!--end container-->
</section><!--end section-->
<!-- Hero End -->

<!-- Shape Start -->
<div class="position-relative">
  <div class="shape overflow-hidden text-white">
    <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
    </svg>
  </div>
</div>
<!--Shape End-->



<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Mes entreprises", entreprises_path, class:"sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Mes réservations", vos_reservations_path, class:"sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Mes rendez-vous", vos_rendez_vous_path, class:"sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
      <div class="panel panel-defautl">
        <div class="panel-heading"> Mes entreprises</div>
        <div class="panel-body">
          <% @entreprises.each do |entreprise| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag entreprise.photos[0].image.url(:thumb) if entreprise.photos.length > 0 %>
            </div>
            <div class="col-md-7">
              <h4><%= link_to entreprise.company_name, entreprise_path(entreprise) %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Mettre à jour", edit_entreprise_path(entreprise), class:"btn btn-primary" %>
            </div>
            <div class="col-md-3 right">
              <%= link_to "supprimer", entreprise_path(entreprise), method: :delete, data: { confirm: "Voulez-vous annuler le rendez-vous ?"}, class:"btn btn-primary" %>
            </div>
          </div>
            <hr>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/entreprises/new.html.erb
<%= content_for :meta_title, "Ajouter une entreprise sur Reparee" %>
<%= content_for :meta_description, "Ajouter une entreprise | #{DEFAULT_META["meta_description"]}" %>



<!-- Shape Start -->
<div class="position-relative">
  <div class="shape overflow-hidden text-white">
    <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
    </svg>
  </div>
</div>
<!--Shape End-->




<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <% if current_user.subscribed? && current_user.entreprises.count < 1 or current_user.premium? %>
          <%= render 'form' %>
        <% else %>
          <!-- Hero Start -->
          <section class="bg-half bg-light d-table w-100">
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-lg-12 text-center">
                  <div class="page-next-level">
                    <h4 class="title"> Ajouter votre entreprise sur Reparee </h4>
                    <div class="page-next">
                      <nav aria-label="breadcrumb" class="d-inline-block">
                        <ul class="breadcrumb bg-white rounded shadow mb-0">
                          <li class="breadcrumb-item"><%= link_to 'Accueil', root_path %></li>
                          <!--<li class="breadcrumb-item"><a href="#">Page</a></li>-->
                          <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Ajout entreprise', new_entreprise_path, :class => "breadcrumb-item active" %></li>
                        </ul>
                      </nav>
                    </div>
                  </div>
                </div>  <!--end col-->
              </div><!--end row-->
            </div> <!--end container-->
          </section><!--end section-->
          <!-- Hero End -->

          <br><br><br><br><br>
                <!-- Profile Sidebar -->
                  <div class="col-md-12 col-lg-12 col-xl-12">

                    <h2 class="text-center">Vous devez être abonnés à la plateforme pour inscrire votre entreprise :
                    <%= link_to 'S\'abonner', abonnement_path %></h2>
                    <h2 class="text-center">Ou</h2>
                    <h2 class="text-center">Si vous avez déjà un abonnement pour ajouter votre entreprise, vous devez passer à l'abonnement premium :
                      <%= link_to 'S\'abonner', abonnement_path %></h2>

                  </div>
          <br><br><br><br><br>
        <% end %>
      </div>
    </div>
  </div>
</div>