config/routes.rb
Rails.application.routes.draw do
  get 'factures/index'

  get 'factures/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{:registrations=>'registrations',
             :confirmations=>'confirmations'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'pages#home'
  resources :users, only: [:show]
  resources :entreprises do
    resources :reservations, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end


  resources :subscribers
  resources :premiums
  resources :contacts, only: [:new, :create]

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  get 'vos_rendez_vous' => 'reservations#your_rdv'
  get 'vos_reservations' => 'reservations#your_reservations'

  get '/search' => 'pages#search'
  get '/faq' => 'pages#faq'
  get '/equipe' => 'pages#equipe'
  get '/services' => 'pages#services'
  get '/success' => 'pages#success'
  get '/abonnement' => 'pages#abonnement'
  get '/accueilsaas' => 'pages#homesaas'
  get '/politique-de-confidentialite' => "pages#politique"
  get '/mentions-legales' => "pages#mentions"
  get '/cgv' => "pages#cgv"

  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format" => "pages#robots"

  resources :factures, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,     :validate => true
  attribute :email,     :validate => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  attribute :sujet,     :validate => true
  attribute :message,     :validate => true

  def headers
    {
        :subject => "Formulaire de contact",
        :to => "edgar.bekier@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :sender, foreign_key: :sender_id, class_name:'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR
     (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/models/entreprise.rb
class Entreprise < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :delete_all
  has_many :reservations, dependent: :delete_all
  has_many :reviews, dependent: :delete_all

  validates :artisan_type, presence: true
  validates :company_name, presence: true
  validates :address, presence: true
  validates :legal_form, presence: true
  validates :siren, presence: true, length: {maximum: 9}
  validates :phone, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

end

app/models/facture.rb
class Facture < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :entreprise

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :entreprise
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :entreprise
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :fullname, presence:true, length: {maximum: 50}

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :entreprises, dependent: :delete_all
  has_many :reservations, dependent: :delete_all
  has_many :reviews, dependent: :delete_all
  has_many :factures, dependent: :delete_all
  has_many :messages, dependent: :delete_all
end

app/controllers/factures_controller.rb
class FacturesController < ApplicationController

  before_action :set_facture, only: [:show]
  before_action :authenticate_user!
  before_action :require_same_user, only: [:show]

  def index
    @factures = current_user.factures
  end

  def show
    @facture = Facture.find(params[:id])
    @user = @facture.user
    @num = rand 1000..10000
    @facture_num = 1

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Facture Num. #{@facture.id}",
               page_size: 'A4',
               template: "factures/show.html.erb",
               layout: "pdf.html",
               orientation: "Landscape",
               lowquality: true,
               zoom: 1,
               dpi: 75
      end
    end
  end

  private
  def set_facture
    @facture = Facture.find(params[:id])
  end

  def require_same_user
    if current_user.id != @facture.user_id
      flash[:danger] = "Vous n'avez pas le droit de consulter cette facture"
      redirect_to root_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/premiums_helper.rb
module PremiumsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/factures/index.html.erb
<!-- Hero Start -->
<section class="bg-half bg-light d-table w-100">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12 text-center">
        <div class="page-next-level">
          <h4 class="title"> Mes factures </h4>
          <div class="page-next">
            <nav aria-label="breadcrumb" class="d-inline-block">
              <ul class="breadcrumb bg-white rounded shadow mb-0">
                <li class="breadcrumb-item"><%= link_to 'Accueil', root_path %></li>
                <!--<li class="breadcrumb-item"><a href="#">Page</a></li>-->
                <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Mes factures', factures_path, :class => "breadcrumb-item active" %></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>  <!--end col-->
    </div><!--end row-->
  </div> <!--end container-->
</section><!--end section-->
<!-- Hero End -->

<!-- Shape Start -->
<div class="position-relative">
  <div class="shape overflow-hidden text-white">
    <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
    </svg>
  </div>
</div>
<!--Shape End-->



<div class="row">

  <div class="col-md-12">
    <div class="panel panel-defautl">
      <div class="panel-heading"> Mes factures</div>
      <div class="panel-body">
        <% @factures.each do |f| %>
          <div class="row">
            <div class="col-md-12">
             <%= link_to "Afficher", facture_path(f) %> facture n° <%= f.id %>
            </div>

          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/factures/show.html.erb
<!-- Invoice Start -->
<section class="bg-invoice bg-light">
  <div class="container">
    <div class="row mt-5 pt-4 pt-sm-0 justify-content-center">
      <div class="col-lg-10">
        <div class="card shadow rounded border-0">
          <div class="card-body">
            <div class=" border-bottom">
              <div class="row">
                <div class="col-md-8">
                  <div class="logo-invoice mb-2"><%= image_tag wicked_pdf_asset_base64('logo-reparee.png'), width: "200px"; %><span class="text-primary">.</span></div>
                  <a href="javascript:void(0)" class="text-primary h6"><i data-feather="link" class="fea icon-sm text-muted me-2"></i>www.reparee.com</a>
                </div><!--end col-->

                <div class="col-md-4 mt-4 mt-sm-0 text-right">
                  <h5>Adresse :</h5>
                  <dl class="row mb-0">
                    <dd class="col-12 text-muted">
                      <a href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d39206.002432144705!2d-95.4973981212445!3d29.709510002925988!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640c16de81f3ca5%3A0xf43e0b60ae539ac9!2sGerald+D.+Hines+Waterwall+Park!5e0!3m2!1sen!2sin!4v1566305861440!5m2!1sen!2sin" data-type="iframe" class="video-play-icon text-muted lightbox">
                        <p class="mb-0">75017, 38 avenue niel, Paris</p>
                       <!-- <p class="mb-0">Redding, CA 96001</p>-->
                      </a>
                    </dd>

                   <!-- <dd class="col-12 text-muted">
                      <a href="mailto:contact@example.com" class="text-muted">info@landrick.com</a>
                    </dd>-->

                   <!-- <dd class="col-12 text-muted">
                      <a href="tel:+152534-468-854" class="text-muted">(+12) 1546-456-856</a>
                    </dd>-->
                  </dl>
                </div><!--end col-->
              </div><!--end row-->
            </div>

            <div class="invoice-middle py-4">
              <h5>Details de la facture :</h5>
              <div class="row mb-0">
                <div class="col-md-8 order-2 order-md-1">
                  <dl class="row">
                    <dt class="col-md-3 col-5 fw-normal">Facture Num :</dt>
                    <dd class="col-md-9 col-7 text-muted"><%= @facture.id %><%= @facture.created_at.strftime('%Y%m%d') %></dd>

                    <dt class="col-md-3 col-5 fw-normal">Nom :</dt>
                    <dd class="col-md-9 col-7 text-muted"><%= @user.fullname %></dd>

                    <!--<dt class="col-md-3 col-5 fw-normal">Address :</dt>
                    <dd class="col-md-9 col-7 text-muted">
                      <p class="mb-0">1962 Pike Street,</p>
                      <p class="mb-0">Diego, CA 92123</p>
                    </dd>-->

                  <!--  <dt class="col-md-3 col-5 fw-normal">Phone :</dt>
                    <dd class="col-md-9 col-7 text-muted">(+45) 4584-458-695</dd>-->
                  </dl>
                </div>

                <div class="col-md-4 order-md-2 order-1 mt-2 mt-sm-0">
                  <dl class="row mb-0">
                    <dt class="col-md-4 col-5 fw-normal">Date :</dt>
                    <dd class="col-md-8 col-7 text-muted"><%= @facture.created_at %></dd>
                  </dl>
                </div>
              </div>
            </div>

            <div class="invoice-table pb-4">
              <div class="table-responsive bg-white shadow rounded">
                <table class="table mb-0 table-center invoice-tb">
                  <thead class="bg-light">
                  <tr>
                    <th scope="col" class="border-bottom text-start">No.</th>
                    <th scope="col" class="border-bottom text-start">Desc</th>
                    <th scope="col" class="border-bottom">Qti</th>
                    <th scope="col" class="border-bottom">Tarif</th>
                    <th scope="col" class="border-bottom">Total</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    <th scope="row" class="text-start"><%= @facture.id %><%= @facture.created_at.strftime('%Y%m%d') %></th>
                    <td class="text-start">Abonnement</td>
                    <td>1</td>
                    <td><%= @facture.montant %></td>
                    <td><%= @facture.montant %></td>
                  </tr>
                  </tbody>
                </table>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-5 ms-auto">
                  <ul class="list-unstyled h6 fw-normal mt-4 mb-0 ms-md-5 ms-lg-4">
                    <!--<li class="text-muted d-flex justify-content-between">Subtotal :<span>$ 22600</span></li>
                    <li class="text-muted d-flex justify-content-between">Taxes :<span> 0</span></li>-->
                    <li class="d-flex justify-content-between">Total :<span><%= @facture.montant %></span></li>
                  </ul>
                </div><!--end col-->
              </div><!--end row-->
            </div>

            <div class="invoice-footer border-top pt-4">
              <div class="row">
                <div class="col-sm-6">
                  <div class="text-sm-start text-muted text-center">
                    <h6 class="mb-0">Services clients : <a href="tel:+152534-468-854" class="text-warning">contact@reparee.com</a></h6>
                  </div>
                </div>

                <!--<div class="col-sm-6">
                  <div class="text-sm-end text-muted text-center">
                    <h6 class="mb-0"><a href="page-terms.html" target="_blank" class="text-primary">Terms & Conditions</a></h6>
                  </div>
                </div>-->
              </div>
            </div>
          </div>
        </div>
      </div><!--end col-->
    </div><!--end row-->
  </div><!--end container-->
</section><!--end section-->
<!-- Invoice End -->