config/routes.rb
Rails.application.routes.draw do
  get 'factures/index'

  get 'factures/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path=>'',
             :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
             :controllers=>{:registrations=>'registrations',
             :confirmations=>'confirmations'
             }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'pages#home'
  resources :users, only: [:show]
  resources :entreprises do
    resources :reservations, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end


  resources :subscribers
  resources :premiums
  resources :contacts, only: [:new, :create]

  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]

  get 'vos_rendez_vous' => 'reservations#your_rdv'
  get 'vos_reservations' => 'reservations#your_reservations'

  get '/search' => 'pages#search'
  get '/faq' => 'pages#faq'
  get '/equipe' => 'pages#equipe'
  get '/services' => 'pages#services'
  get '/success' => 'pages#success'
  get '/abonnement' => 'pages#abonnement'
  get '/accueilsaas' => 'pages#homesaas'
  get '/politique-de-confidentialite' => "pages#politique"
  get '/mentions-legales' => "pages#mentions"
  get '/cgv' => "pages#cgv"

  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format" => "pages#robots"

  resources :factures, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,     :validate => true
  attribute :email,     :validate => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  attribute :sujet,     :validate => true
  attribute :message,     :validate => true

  def headers
    {
        :subject => "Formulaire de contact",
        :to => "edgar.bekier@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :sender, foreign_key: :sender_id, class_name:'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name:'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
  end

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR
     (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/models/entreprise.rb
class Entreprise < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :delete_all
  has_many :reservations, dependent: :delete_all
  has_many :reviews, dependent: :delete_all

  validates :artisan_type, presence: true
  validates :company_name, presence: true
  validates :address, presence: true
  validates :legal_form, presence: true
  validates :siren, presence: true, length: {maximum: 9}
  validates :phone, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end

end

app/models/facture.rb
class Facture < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :entreprise

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :entreprise
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :entreprise
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :fullname, presence:true, length: {maximum: 50}

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :entreprises, dependent: :delete_all
  has_many :reservations, dependent: :delete_all
  has_many :reviews, dependent: :delete_all
  has_many :factures, dependent: :delete_all
  has_many :messages, dependent: :delete_all
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  before_action :authenticate_user!

  def new

  end

  def update

    token = params[:stripeToken]

    customer = Stripe::Customer.create(
        card: token,
        plan: 2177,
        email: current_user.email
    )

    current_user.subscribed = true
    current_user.stripeid = customer.id
    current_user.save

    current_user.factures.create(user_id: current_user.id, mail: current_user.email, montant: "59", name: current_user.fullname)

    redirect_to root_path


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_subscriber_path


  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/factures_helper.rb
module FacturesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/premiums_helper.rb
module PremiumsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_path(1), method: :put, id: "payment-form" do %>
  <!-- Hero Start -->
  <section class="bg-half bg-light d-table w-100">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12 text-center">
          <div class="page-next-level">
            <h4 class="title"> Abonnement </h4>
            <div class="page-next">
              <nav aria-label="breadcrumb" class="d-inline-block">
                <ul class="breadcrumb bg-white rounded shadow mb-0">
                  <li class="breadcrumb-item"><%= link_to 'Accueil', root_path %></li>
                  <!--<li class="breadcrumb-item"><a href="#">Page</a></li>-->
                  <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Abonnement', abonnement_path, :class => "breadcrumb-item active" %></li>
                </ul>
              </nav>
            </div>
          </div>
        </div>  <!--end col-->
      </div><!--end row-->
    </div> <!--end container-->
  </section><!--end section-->
  <!-- Hero End -->

  <!-- Shape Start -->
  <div class="position-relative">
    <div class="shape overflow-hidden text-white">
      <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
      </svg>
    </div>
  </div>
  <!--Shape End-->
  <div class="container mt-100 mt-60">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="section-title text-center mb-4 pb-2">
          <h4 class="title mb-4">Enregistrer votre entreprise</h4>
          <p class="text-muted para-desc mb-0 mx-auto">Démarrer votre collaboration avec <span class="text-primary font-weight-bold">Reparee</span> pour générer des clients rapidement.</p>
        </div>
      </div><!--end col-->
    </div><!--end row-->

    <div class="row align-items-end">
      <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">

      </div><!--end col-->

      <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
        <div class="pricing text-center rounded overflow-hidden shadow-lg">
          <div class="price-header border-bottom bg-primary pt-5 pb-5">
            <h1 class="text-white-50"><i class="uil uil-award"></i></h1>
            <h5 class="price-title text-white">Professionnel</h5>
            <p class="mb-0 text-light">Idéal pour les petites entreprises</p>
          </div>
          <div class="border-bottom py-5">
            <h2 class="font-weight-bold">€ 59.00</h2>
            <h6 class="text-muted mb-0 font-weight-normal">Par mois et par utilisateur</h6>
            <%#  <%= link_to 'Souscrire', new_subscriber_path, :class => "btn btn-primary mt-4" %>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button abonnement-btn"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-name="Reparee Professionnel"
                    data-description="Abonnement mensuel"
                    data-panel-label="59€/mois"
                    data-label="Paiement par carte"
                    data-locale="fr"></script>

          </div>
          <div class="pricing-features text-left p-4">
            <h5>Inclus dans l'offre:</h5>
            <ul class="feature list-unstyled mb-0">
              <li class="text-muted"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>1 entreprise</li>
              <li class="text-muted mt-2"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>Accès à vie</li>
              <li class="text-muted mt-2"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>Accessible directement dans les résultats de recherche</li>
              <li class="text-muted mt-2"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>24/7 Support</li>
              <li class="text-muted mt-2"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>Gestion des RDV</li>
            </ul>
          </div>
        </div><!--end price three-->
      </div><!--end col-->


      <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">

      </div><!--end col-->
    </div><!--end row-->
  </div><!--end container-->

  <br><br><br>

<% end %>
<script>
    $(function() {
        $(".stripe-button-el").replaceWith('<button type="submit" class="btn btn-primary mt-4">Payer</button>');
    });
</script>

app/views/subscribers/new.html.erb
          <% if current_user.subscribed? %>
              <!-- Hero Start -->
              <section class="bg-half bg-light d-table w-100">
                <div class="container">
                  <div class="row justify-content-center">
                    <div class="col-lg-12 text-center">
                      <div class="page-next-level">
                        <h4 class="title">Abonnement</h4>
                        <div class="page-next">
                          <nav aria-label="breadcrumb" class="d-inline-block">
                            <ul class="breadcrumb bg-white rounded shadow mb-0">
                              <li class="breadcrumb-item"><%= link_to 'Accueil', root_path %></li>
                              <!--<li class="breadcrumb-item"><a href="#">Page</a></li>-->
                              <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Abonnement', abonnement_path, :class => "breadcrumb-item active" %></li>
                            </ul>
                          </nav>
                        </div>
                      </div>
                    </div>  <!--end col-->
                  </div><!--end row-->
                </div> <!--end container-->
              </section><!--end section-->
              <!-- Hero End -->

              <!-- Shape Start -->
              <div class="position-relative">
                <div class="shape overflow-hidden text-white">
                  <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
                  </svg>
                </div>
              </div>
              <!--Shape End-->
              <div class="container mt-100 mt-60">
                <div class="row justify-content-center">
                  <div class="col-12">
                    <div class="section-title text-center mb-4 pb-2">
                      <h4 class="title mb-4">Vous êtes déjà abonné à cette offre</h4>
                      <!--<p class="text-muted para-desc mb-0 mx-auto">Démarrer votre collaboration avec <span class="text-primary font-weight-bold">Reparee</span> pour générer des clients rapidement.</p>-->
                    </div>
                  </div><!--end col-->
                </div><!--end row-->

                <div class="row align-items-end">
                  <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">

                  </div><!--end col-->

                  <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
                    <div class="pricing text-center rounded overflow-hidden shadow-lg">
                      <div class="price-header border-bottom bg-primary pt-5 pb-5">
                        <h1 class="text-white-50"><i class="uil uil-award"></i></h1>
                        <h5 class="price-title text-white">Professionnel</h5>
                        <p class="mb-0 text-light">Idéal pour les petites entreprises</p>
                      </div>
                      <div class="border-bottom py-5">
                        <h2 class="font-weight-bold">€ 59.00</h2>
                        <h6 class="text-muted mb-0 font-weight-normal">Par mois et par utilisateur</h6>
                        <%#  <%= link_to 'Souscrire', new_subscriber_path, :class => "btn btn-primary mt-4" %>

                      </div>
                      <div class="pricing-features text-left p-4">
                        <h5>Ce qui est inclus:</h5>
                        <ul class="feature list-unstyled mb-0">
                          <li class="text-muted"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>1 entreprise</li>
                          <li class="text-muted mt-2"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>Accès à vie</li>
                          <li class="text-muted mt-2"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>Accessible directement dans les résultats de recherche</li>
                          <li class="text-muted mt-2"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>24/7 Support</li>
                          <li class="text-muted mt-2"><i data-feather="arrow-right" class="fea icon-sm text-primary mr-2"></i>Gestion des RDV</li>
                        </ul>
                      </div>
                    </div><!--end price three-->
                  </div><!--end col-->


                  <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">

                  </div><!--end col-->
                </div><!--end row-->
              </div><!--end container-->

              <br><br><br>

          <% else %>
            <!--<h2>Souscription à l'abonnement</h2>-->
            <%= render 'subscribers/form' %>
          <% end %>